// Package healthv1api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version 2.3.0 DO NOT EDIT.
package healthv1api

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// Defines values for SleepType.
const (
	Awake SleepType = "awake"
	Deep  SleepType = "deep"
	Light SleepType = "light"
	Rem   SleepType = "rem"
)

// DataPoint defines model for DataPoint.
type DataPoint struct {
	// Timestamp Unix timestamp in seconds
	Timestamp Timestamp `json:"timestamp"`

	// Value Value of the data point
	Value float64 `json:"value"`
}

// EstrogenData Estrogen level of the pet
type EstrogenData struct {
	// DosageHistory When the estrogen was administered, represented as a list of
	// timestamps.
	DosageHistory []Timestamp `json:"dosageHistory"`

	// Levels Estimated estrogen levels of the pet
	Levels Measurement `json:"levels"`

	// Type Type of estrogen (e.g. patches, pills, injection)
	Type string `json:"type"`
}

// HealthData defines model for HealthData.
type HealthData struct {
	// Estrogen Estrogen level of the pet
	Estrogen *EstrogenData `json:"estrogen,omitempty"`

	// HeartRate Heart rate of the pet
	HeartRate *Measurement `json:"heartRate,omitempty"`

	// Sleep Sleep data of the pet
	Sleep *SleepData `json:"sleep,omitempty"`

	// Steps Steps taken by the pet
	Steps *Measurement `json:"steps,omitempty"`
}

// Measurement defines model for Measurement.
type Measurement struct {
	// Points List of data points
	Points []DataPoint `json:"points"`

	// Unit Unit of the data points
	Unit string `json:"unit"`
}

// SleepData Sleep data of the pet
type SleepData = []struct {
	// SleepType Type of sleep
	SleepType SleepType `json:"sleepType"`

	// Timestamp Unix timestamp in seconds
	Timestamp Timestamp `json:"timestamp"`
}

// SleepType Type of sleep
type SleepType string

// Timestamp Unix timestamp in seconds
type Timestamp = int64

// GetLatestHealthDataParams defines parameters for GetLatestHealthData.
type GetLatestHealthDataParams struct {
	// Range The time range to fetch the data for in days as a floating point
	// number.
	Range *float32 `form:"range,omitempty" json:"range,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /latest.json)
	GetLatestHealthData(w http.ResponseWriter, r *http.Request, params GetLatestHealthDataParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /latest.json)
func (_ Unimplemented) GetLatestHealthData(w http.ResponseWriter, r *http.Request, params GetLatestHealthDataParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetLatestHealthData operation middleware
func (siw *ServerInterfaceWrapper) GetLatestHealthData(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLatestHealthDataParams

	// ------------- Optional query parameter "range" -------------

	err = runtime.BindQueryParameter("form", true, false, "range", r.URL.Query(), &params.Range)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "range", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLatestHealthData(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/latest.json", wrapper.GetLatestHealthData)
	})

	return r
}

type GetLatestHealthDataRequestObject struct {
	Params GetLatestHealthDataParams
}

type GetLatestHealthDataResponseObject interface {
	VisitGetLatestHealthDataResponse(w http.ResponseWriter) error
}

type GetLatestHealthData200JSONResponse HealthData

func (response GetLatestHealthData200JSONResponse) VisitGetLatestHealthDataResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /latest.json)
	GetLatestHealthData(ctx context.Context, request GetLatestHealthDataRequestObject) (GetLatestHealthDataResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetLatestHealthData operation middleware
func (sh *strictHandler) GetLatestHealthData(w http.ResponseWriter, r *http.Request, params GetLatestHealthDataParams) {
	var request GetLatestHealthDataRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLatestHealthData(ctx, request.(GetLatestHealthDataRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLatestHealthData")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLatestHealthDataResponseObject); ok {
		if err := validResponse.VisitGetLatestHealthDataResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
