# yaml-language-server: $schema=https://raw.githubusercontent.com/deepmap/oapi-codegen/HEAD/configuration-schema.json
package: openapi
output: ""
generate:
  models: true
  chi-server: true
  strict-server: true
