#!/usr/bin/env sh
bold()   { printf '\e[1m%s\e[0m' "$1"; }
dark()   { printf '\e[3%dm%s\e[0m' "$1" "$2"; }
light()  { printf '\e[9%dm%s\e[0m' "$1" "$2"; }
faint()  { printf '\e[2m%s\e[0m' "$1"; }
hidden() { printf '\e[8m%s\e[0m' "$1"; }

clear
neofetch
echo
echo -e "Welcome to $(light 5 "$(bold "libdb.so")") $(light 5 "<3")"
echo -e "Type $(bold "help") for a list of commands, also try $(bold "cd"), $(bold "ls"), $(bold "cat") $(faint "$(dark 0 "and $(bold nsfw)")")"

sizes=( $(termsize) )
width=${sizes[0]}
if (( width > 80 )); then
	width=80
fi

echo
webring -w $width

echo
if [ $(nsfw get) == true ]; then
	echo -e "hey!! just a heads up, you have \e[1mnsfw\e[0m mode enabled!"
fi
