name: Build
on:
  push:
  pull_request:
  workflow_call:
  workflow_dispatch:
jobs:
  gomod2nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Tidy Go modules
        run: |-
          nix develop -c go mod tidy

      - name: Update gomod2nix
        run: |-
          nix develop -c gomod2nix

          if [[ $(git status --porcelain) ]]; then
            echo "updated=1" >> $GITHUB_OUTPUT
          fi

      - name: Commit changes (if any)
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: |-
            Update gomod2nix.toml

            Update based on revision ${{ github.sha }}.
          branch: ${{ github.ref_name }}

  build:
    runs-on: ubuntu-latest
    needs: gomod2nix
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build
        run: nix build .#

      - name: Upload artifact(s)
        uses: actions/upload-pages-artifact@v3
        with:
          path: result
