name: Build
on:
  # no push because deploy.yml will trigger this workflow
  pull_request:
  workflow_call:
  workflow_dispatch:
jobs:
  gomod2nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Nix shell
        uses: diamondburned/cache-install@main
        with:
          nix-file: "" # we don't need this yet
          shell-file: shell.nix
          auto-optimise: true

      - name: Tidy Go modules
        run: go mod tidy

      - name: Update gomod2nix
        id: gomod2nix
        run: |-
          gomod2nix

          if [[ $(git status --porcelain) ]]; then
            echo "updated=1" >> $GITHUB_OUTPUT
          fi

      - name: Commit changes (if any)
        id: commit
        if: ${{ steps.gomod2nix.outputs.updated == 1 }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: |-
            Update gomod2nix.toml

            Update based on revision ${{ github.sha }}.
          branch: ${{ github.ref_name }}

  build:
    runs-on: ubuntu-latest
    needs: gomod2nix
    steps:
      - uses: actions/checkout@v3

      - name: Cache Nix package builds
        uses: diamondburned/cache-install@main
        with:
          # We only need our default.nix expression and not shell.nix.
          nix-file: ""
          shell-file: ""
          instantiated-expression: import ./. {}
          auto-optimise: true

      - name: Build
        run: echo output=$(nix-build) >> $GITHUB_OUTPUT

      - name: Upload artifact(s)
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{ steps.build.outputs.output }}
